package in.retalemine;

import java.util.Arrays;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.AbstractSelect.NewItemHandler;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class BillingComponent extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	private Table billableItems = new Table("Billing Cart");

	public BillingComponent() {
		setCompositionRoot(buildMainLayout());
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		setWidth("100.0%");
		setHeight("100.0%");

		mainLayout.addComponent(buildBillingHeader());
		mainLayout.addComponent(buildAddToCart());
		mainLayout.addComponent(buildBillingTable());
		
		return mainLayout;
	}

	private Component buildBillingTable() {
		VerticalLayout billingLayout = new VerticalLayout();

		billableItems.addContainerProperty("SNo#", Integer.class, null);
		billableItems.addContainerProperty("Product Description", String.class, "");
		billableItems.addContainerProperty("Unit Price", Double.class, 0.0);
		billableItems.addContainerProperty("Quantity", String.class, "1");
		billableItems.addContainerProperty("Net Price", Double.class, 0.0);
		billableItems.setPageLength(5);
		billableItems.setWidth("100%");
		billableItems.setFooterVisible(true);
		billableItems.setColumnFooter("Quantity", "Net Price");
		billableItems.setColumnFooter("Net Price", "0.0");

		billingLayout.setImmediate(false);
		billingLayout.setWidth("100%");
		billingLayout.setHeight("100%");
		billingLayout.setMargin(false);
		billingLayout.setSpacing(true);

		billingLayout.addComponent(billableItems);

		return billingLayout;
	}

	private Component buildAddToCart() {
		HorizontalLayout addToCartLayout = new HorizontalLayout();
		final ComboBox productNameCB = new ComboBox("Product List",Arrays.
				asList(new String[] { "Lux Sandal", "Hamam","Cinthol Old" }));
		final ComboBox productPriceCB = new ComboBox("Price List",
				Arrays.asList(new Double[] { 10.0, 20.0, 30.0, 40.0, 50.0 }));
		final TextField qty = new TextField("Quantity");
		final ComboBox qtySuffixCB = new ComboBox("Qty Suffix List",
				Arrays.asList(new String[] { "pcs", "kg", "lt" }));
		final Button addToCartBT = new Button("Add to cart");

		productNameCB.setInputPrompt("Enter a product name");
		productNameCB.setFilteringMode(FilteringMode.CONTAINS);
		productNameCB.setImmediate(true);
		productNameCB.setRequired(true);
		productNameCB.setPageLength(10);
		//productNameCB.setScrollToSelectedItem(true);
		productNameCB.setNullSelectionAllowed(true);
		/*String nullitem = "-- none --";
		productNameCB.addItem(nullitem);
		productNameCB.setNullSelectionItemId(nullitem);*/
		productNameCB.setNewItemsAllowed(true);
		productNameCB.setNewItemHandler(new NewItemHandler() {
			@Override
			public void addNewItem(String newProductName) {
				StringBuffer camelCasePName = new StringBuffer();
				Matcher camelCaseMatcher = Pattern.compile("([a-z])([a-z]*)",
						Pattern.CASE_INSENSITIVE).matcher(
						newProductName.trim().replaceAll("\\s+", " "));
				while (camelCaseMatcher.find()) {
					camelCaseMatcher.appendReplacement(camelCasePName,
							camelCaseMatcher.group(1).toUpperCase()
									+ camelCaseMatcher.group(2).toLowerCase());
				}
				camelCaseMatcher.appendTail(camelCasePName);
				productNameCB.addItem(camelCasePName.toString());
				productNameCB.setValue(camelCasePName.toString());
			}
		});

		productPriceCB.setInputPrompt("Select price");
		productPriceCB.setFilteringMode(FilteringMode.STARTSWITH);
		productPriceCB.setImmediate(true);
		productPriceCB.setRequired(true);
		productPriceCB.setPageLength(10);
		productPriceCB.setNullSelectionAllowed(true);
		productPriceCB.setNewItemsAllowed(true);
		productPriceCB.setNewItemHandler(new NewItemHandler() {
			@Override
			public void addNewItem(String newPrice) {
				Double parsedPrice = Double.parseDouble(newPrice.trim());
				productPriceCB.addItem(parsedPrice);
				productPriceCB.setValue(parsedPrice);
			}
		});

		qty.setInputPrompt("Enter Quantity");
		qty.setRequired(true);

		qtySuffixCB.setInputPrompt("Select Unit");
		qtySuffixCB.setFilteringMode(FilteringMode.STARTSWITH);
		qtySuffixCB.setImmediate(true);
		qtySuffixCB.setRequired(true);
		qtySuffixCB.setPageLength(10);
		qtySuffixCB.setNullSelectionAllowed(true);
		qtySuffixCB.setNewItemsAllowed(true);
		qtySuffixCB.setNewItemHandler(new NewItemHandler() {
			@Override
			public void addNewItem(String newQtySuffix) {
				qtySuffixCB.addItem(newQtySuffix.trim().toLowerCase()
						.replaceAll("\\s+", ""));
				qtySuffixCB.setValue(newQtySuffix.trim().toLowerCase()
						.replaceAll("\\s+", ""));
			}
		});

		addToCartBT.addClickListener(new Button.ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				final Object[] productInfo = new Object[5];
				productInfo[0] = billableItems.size() + 1;
				productInfo[1] = productNameCB.getValue();
				productInfo[2] = productPriceCB.getValue();
				productInfo[3] = qty.getValue();
				productInfo[4] = (Double) productPriceCB.getValue()
						* Double.parseDouble(qty.getValue());
				billableItems.addItem(productInfo, billableItems.size());
				billableItems.setCurrentPageFirstItemId(billableItems.size()
						- billableItems.getPageLength());
				billableItems.setColumnFooter("Net Price", String
						.valueOf(Double.parseDouble(billableItems
								.getColumnFooter("Net Price"))
								+ (Double) productInfo[4]));
				resetAddToCart();
			}

			private void resetAddToCart() {
				productNameCB.setValue(null);
				productPriceCB.setValue(null);
				qty.setValue("");
				qtySuffixCB.setValue(null);
			}
		});

		addToCartLayout.setImmediate(false);
		addToCartLayout.setWidth("100%");
		addToCartLayout.setHeight("100%");
		addToCartLayout.setMargin(false);
		addToCartLayout.setSpacing(true);

		addToCartLayout.addComponent(productNameCB);
		addToCartLayout.addComponent(productPriceCB);
		addToCartLayout.addComponent(qty);
		addToCartLayout.addComponent(qtySuffixCB);
		addToCartLayout.addComponent(addToCartBT);

		return addToCartLayout;
	}

	private Component buildBillingHeader() {
		HorizontalLayout billingHeaderLayout = new HorizontalLayout();
		HorizontalLayout billNoLayout = new HorizontalLayout();
		HorizontalLayout billDateLayout = new HorizontalLayout();
		Label billNoCaption = new Label();
		Label billNo = new Label();
		Label billDateCaption = new Label();
		DateField billDate = new DateField();

		billingHeaderLayout.setImmediate(false);
		billingHeaderLayout.setWidth("100%");
		billingHeaderLayout.setHeight("100%");
		billingHeaderLayout.setMargin(false);
		billNoLayout.setSpacing(true);
		billDateLayout.setSpacing(true);

		billNoCaption.setValue("Bill No#");
		billNo.setValue("1");
		billDateCaption.setValue("Date:");
		billDate.setValue(new Date());
		billDate.setReadOnly(true);
		billDate.setDateFormat("dd-MM-yyyy");

		billingHeaderLayout.addComponent(billNoLayout);
		billingHeaderLayout.setComponentAlignment(billNoLayout,
				Alignment.MIDDLE_LEFT);
		billingHeaderLayout.addComponent(billDateLayout);
		billingHeaderLayout.setComponentAlignment(billDateLayout,
				Alignment.MIDDLE_RIGHT);

		billNoLayout.addComponent(billNoCaption);
		billNoLayout.addComponent(billNo);

		billDateLayout.addComponent(billDateCaption);
		billDateLayout.addComponent(billDate);
		return billingHeaderLayout;
	}
}
